name: autofix.ci

on:
  pull_request:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo foo > foo.txt
      - run: chmod +x foo.txt
      - uses: autofix-ci/action@comments
        with:
          comment: |
            This is a multi-line test
            for adding a custom comment.

            Yay! ✨
