name: autofix.ci

on: [ pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo foo > foo.txt
      - run: chmod +x foo.txt
      - uses: autofix-ci/action@dev
