# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo foo > foo.txt
      - uses: autofix-ci/action@main
